Echo 79 royalties management
rarible/tezos-api pull request #2
Opened 2022-04-14 13:23 UTC by f-pto

2022-04-14 17:12 UTC, mystdeim requested changes

2022-04-14 17:12 UTC, mystdeim commented on client-tzkt/build.gradle.kts
> +    implementation ("com.google.code.gson:gson:2.9.0")
Could we do not include additional dependecy and use jackson?

2022-04-14 17:12 UTC, mystdeim commented on client-tzkt/src/main/kotlin/com/rarible/tzkt/model/BigMapKey.kt
> +    val id: kotlin.Int? = null,
we don't need to include kontin prefix

2022-04-14 17:12 UTC, mystdeim commented on client-tzkt/src/main/kotlin/com/rarible/tzkt/model/BigMapKey.kt
> +    @Json(name = "id")
I think we can omit this annotation and other below

2022-04-14 17:12 UTC, mystdeim commented on client-tzkt/src/main/kotlin/com/rarible/tzkt/royalties/RoyaltiesHandler.kt
> +            runBlocking {
Why do we need blocking here?

2022-04-14 17:12 UTC, mystdeim commented on client-tzkt/src/main/kotlin/com/rarible/tzkt/royalties/RoyaltiesHandler.kt
> +            runBlocking {
Maybe we can declare method as suspend and do not use runBlocking?

2022-04-14 17:12 UTC, mystdeim commented on client-tzkt/src/main/kotlin/com/rarible/tzkt/royalties/RoyaltiesHandler.kt
> +        } catch (e: Exception){}
it's bad practise to ignore exception. It's better to log it at least

2022-04-14 21:23 UTC, f-pto commented on client-tzkt/src/main/kotlin/com/rarible/tzkt/royalties/RoyaltiesHandler.kt
> +        } catch (e: Exception){}
I added that temporarily because the tzkt clients send non nullable fields, so I was going to only add logs here. Shall I make the result of the clients nullable ?

2022-04-19 06:30 UTC, mystdeim requested changes

2022-04-19 06:30 UTC, mystdeim commented on tzkt-client/src/main/kotlin/com/rarible/tzkt/model/BigMapKey.kt
> +import com.squareup.moshi.Json
It seems unused, remove please

2022-04-19 06:30 UTC, mystdeim commented on tzkt-client/src/main/kotlin/com/rarible/tzkt/model/BigMapKey.kt
> +@file:Suppress(
remove please, it's not good to suppress helpful checking

2022-04-19 06:30 UTC, mystdeim commented on tzkt-client/src/main/kotlin/com/rarible/tzkt/royalties/RoyaltiesHandler.kt
> +    suspend fun processRoyalties(id: String): List<Part> {
How can we use this? I think we can call this method from TokenClient

2022-04-19 11:05 UTC, mystdeim approved these changes

2022-04-19 11:06 UTC, merged